specfile_path: gnome-abrt.spec
files_to_sync:
  - .packit.yml
  - gnome-abrt.spec
upstream_package_name: gnome-abrt
upstream_project_url: https://github.com/abrt/gnome-abrt
downstream_package_name: gnome-abrt
jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
    - fedora-all
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
