#!/usr/bin/env python

import os
import sys
import logging

# pygobject
from gi.repository import Gtk
from gi.repository import GLib

# oops
import config
import views
import problems
import dbus_problems
import directory_problems
import controller
import errors
import l10n

class OopsApplication(Gtk.Application):
    
    def __init__(self):
        super(OopsApplication, self).__init__()

        conf = config.get_configuration()
        conf.add_option("all_problems", default_value=False)

        sources = []
        try:
            sources.append(dbus_problems.DBusProblemSource())
        except errors.UnavailableSource as e:
            logging.warning(e.message)

        # TODO : really ? move it somewhere else ...
        self.gcontext = GLib.main_context_default()
        try:
            # TODO : pass the directory over command line
            sources.append(directory_problems.DirectoryProblemSource(os.path.join(GLib.get_user_cache_dir(), "abrt/spool"), context=self.gcontext))
        except errors.UnavailableSource as e:
            logging.warning(e.message)

        if len(sources) == 0:
            raise errors.UnavailableSource("No available problem source.")

        self.source = problems.MultipleSources(*sources)

    def do_activate(self):
        self.window = views.OopsWindow(self, self.source, controller.Controller(self.source))
        self.window.connect("delete-event", self.on_window_delete_event)
        self.window.show_all()

    def on_window_delete_event(self, widget, data):
        self.quit()


if __name__ == "__main__":
    l10n.init('gnome_abrt')
    #logging.getLogger().setLevel(logging.DEBUG)
    app = None
    try:
        app = OopsApplication()
    except errors.UnavailableSource as e:
        logging.error(e.message)
        sys.exit(1)

    exit_code = app.run(sys.argv)
    sys.exit(exit_code)
