name: Run Pylint
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  check:
    container:
      image: fedora:latest
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v3

      - name: Install build environment
        run: dnf --assumeyes install dnf-plugins-core python3-pylint tito

      - name: Install build dependencies
        run: dnf --assumeyes builddep --spec gnome-abrt.spec

      - name: Configure build
        run: meson setup build

      - name: Build and install packages
        run: ninja -v -C build

      - name: Run Pylint
        run: meson test -C build --print-errorlogs lint
