name: Run pylint
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  check:
    container:
      image: fedora:latest
    runs-on: ubuntu-latest
    steps:
      - name: Install git
        run: dnf --assumeyes install git

      - name: Check out sources
        uses: actions/checkout@v2

      - name: Install build environment
        run: dnf --assumeyes install dnf-plugins-core tito

      - name: Install build dependencies
        run: dnf builddep --assumeyes --spec gnome-abrt.spec

      - name: Configure build
        run: meson setup build

      - name: Build and install packages
        run: |
            meson compile -C build rpm -v
            dnf --assumeyes install ./build/rpm/**/*.rpm

      - name: Run pylint
        run: meson test -C build --print-errorlogs lint
